name: "Build"
description: "Common step for building rust application"

runs:
  using: "composite"

  steps:
    - uses: Swatinem/rust-cache@v2
    - uses: cargo-bins/cargo-binstall@main
    - name: Install nextest
      shell: bash
      run: cargo binstall cargo-nextest --secure
