name: "Build"
description: "Common step for building rust application"

runs:
  using: "composite"

  steps:
    # Common
    - uses: Swatinem/rust-cache@v2
    # Sccache
    - name: Install sccache
      if: runner.os == 'Linux'
      shell: bash
      run: sudo apt-get install sccache
    - name: Configure sccache
      if: runner.os == 'Linux'
      uses: actions/github-script@v7
      with:
        script: |
          core.exportVariable('ACTIONS_RESULTS_URL', process.env.ACTIONS_RESULTS_URL || '');
          core.exportVariable('ACTIONS_RUNTIME_TOKEN', process.env.ACTIONS_RUNTIME_TOKEN || '');
    # Nextest
    - uses: cargo-bins/cargo-binstall@main
    - name: Install nextest
      shell: bash
      run: cargo binstall cargo-nextest --secure
