[package]
name = "coinbase-fix42-order-entry"
version = "0.2.0"
edition = "2021"
publish = false

[dependencies]
quickfix = { path = "../../quickfix", version = "0.2.0" }

[build-dependencies]
quickfix-msg-gen = { path = "../../quickfix-msg-gen", version = "0.2.0" }
