[test-groups]
serial-integration = { max-threads = 1 }

[[profile.default.overrides]]
filter = 'package(quickfix) + test(test_log_factory)'
test-group = 'serial-integration'

[[profile.default.overrides]]
filter = 'package(quickfix) + test(test_send_receive)'
test-group = 'serial-integration'
