name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always
  SCCACHE_GHA_ENABLED: on
  SCCACHE_GHA_VERSION: "1"

jobs:
  build_and_test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - uses: ./.github/actions/builder
      - uses: ./.github/actions/rustcSetup
      - name: Build debug
        run: cargo build --verbose
      - name: Build release
        run: cargo build --verbose --release
      - name: Run tests no default features
        run: cargo nextest run --no-default-features
      - name: Run tests
        run: cargo nextest run

  test_ssl:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - uses: ./.github/actions/builder
      - uses: ./.github/actions/rustcSetup
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install --yes libssl-dev
      - name: Run tests
        run: cargo nextest run -F build-with-ssl

  test_mysql:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - uses: ./.github/actions/builder
      - uses: ./.github/actions/rustcSetup
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install --yes libmysqlclient-dev
      - name: Run tests
        run: cargo nextest run -F build-with-mysql

  test_postgresql:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - uses: ./.github/actions/builder
      - uses: ./.github/actions/rustcSetup
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install --yes libpq-dev
      - name: Run tests
        run: cargo nextest run -F build-with-postgres

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - uses: ./.github/actions/builder
      - name: Lint
        run: cargo clippy
      - name: Format
        run: cargo fmt --check
